### ISSUE TITLE
Cannot compile on ubuntu 18.04 due redefined _GNU_SOURCE

### ISSUE THREAD

**Issue by jjvbsag** [LuaLanes/lanes#171]
Cannot compile on ubuntu 18.04 due redefined `_GNU_SOURCE`

Test 
```sh
rm -rf lanes
git clone https://github.com/LuaLanes/lanes.git
cd lanes && make
```
Result
```
make[1]: Entering directory '.../lanes/src'
cc -Wall -Werror -O2 -I/usr/include/lua5.1 -D_GNU_SOURCE -fPIC   -c -o lanes.o lanes.c
cc -Wall -Werror -O2 -I/usr/include/lua5.1 -D_GNU_SOURCE -fPIC   -c -o compat.o compat.c
cc -Wall -Werror -O2 -I/usr/include/lua5.1 -D_GNU_SOURCE -fPIC   -c -o threading.o threading.c
threading.c:38:0: error: "_GNU_SOURCE" redefined [-Werror]
 # define _GNU_SOURCE /* must be defined before any include */
 ^
<command-line>:0:0: note: this is the location of the previous definition
cc1: all warnings being treated as errors
<builtin>: recipe for target 'threading.o' failed
make[1]: *** [threading.o] Error 1
make[1]: Leaving directory '.../lanes/src'
Makefile:46: recipe for target 'src/lanes/core.so' failed
make: *** [src/lanes/core.so] Error 2
```
This is the fix
```diff
diff --git a/src/threading.c b/src/threading.c
index 1eab52f..4eb4e40 100644
--- a/src/threading.c
+++ b/src/threading.c
@@ -35,7 +35,6 @@ THE SOFTWARE.
 ===============================================================================
 */
 #if defined(__linux__)
-# define _GNU_SOURCE /* must be defined before any include */
 # ifdef __ANDROID__
 #  include <android/log.h>
 #  define LOG_TAG "LuaLanes"
```
Please check for side effects.

I assume this was introduced by #166 which conflicts with the define in the Makefile, where there is a
```Makefile
ifeq "$(shell uname -s)" "Linux"
  # -D_GNU_SOURCE needed for 'pthread_mutexattr_settype'
  CFLAGS += -D_GNU_SOURCE -fPIC
:::
```
