### ISSUE TITLE
lanes fails to build on Linux x86_64 (gcc 4.6.1) size_t vs int size

### ISSUE THREAD

**Issue by harningt** [LuaLanes/lanes#15]
```
cc -Wall -Werror -O2 -I/usr/include/lua5.1   -D_GNU_SOURCE -fPIC   -c -o tools.o tools.c
tools.c: In function ‘lookup_native_func’:
tools.c:1224:3: error: field width specifier ‘*’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ [-Werror=format]
cc1: all warnings being treated as errors
```
